#' Show all jobs
#'
#' It show all Jobs (run, succeded or failed) invoked by user
#'
#' @import httr
#' @param url string url of server: It must contain the server address 
#' and base url; service name is added automatically
#'
#' @return list of jobs
#' Every job in the list is identified by:
#' \itemize{
#' \item{id: unique job identifier}
#' }
#'
#' @seealso \code{\link{show_job_log}} @seealso \code{\link{stop_job}} 
#' @seealso \code{\link{trace_job}}
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#'
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' list_jobs <- show_jobs_list(remote_url)
#'
#' @export
#'
show_jobs_list <- function(url)
{
    URL <- paste0(url,"/jobs")
    h <- c('X-Auth-Token' = authToken)
    req <- httr::GET(URL, httr::add_headers(h))
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content$error)
    else
        return(content)
}

#' Show a job log
#'
#' It show a job log for specific job
#'
#'
#' @import httr
#' @param url string url of server: It must contain the server address
#' and base url; service name is added automatically
#' @param job_id string id of the job
#'
#' @return log text
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#'
#' \dontrun{
#' 
#' ## login with guest user
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' 
#' ## list all jobs
#' list_jobs <- show_jobs_list(remote_url)
#' jobs_1 <- list_jobs$jobs[[1]]
#' 
#' ## show log
#' show_job_log(remote_url, jobs_1)
#' 
#' }
#' 
#' @export
#'
show_job_log <- function(url, job_id)
{
    URL <- paste0(url,"/jobs/",job_id,"/log")
    h <- c('X-Auth-Token' = authToken,'Accept'= 'Application/json')
    req <- httr::GET(URL, httr::add_headers(h))
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content$error)
    else
        print(unlist(content,use.names = FALSE))
}

#' Stop a job
#'
#' It stops a specific current job
#'
#' @import httr
#' @param url string url of server: It must contain the server address 
#' and base url; service name is added automatically
#' @param job_id string id of the job
#'
#' @return None
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#'
#' \dontrun{
#' 
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' list_jobs <- show_jobs_list(remote_url)
#' jobs_1 <- list_jobs$jobs[[1]]
#' stop_job(remote_url, jobs_1)
#' }
#' 
#' @export
#'
stop_job <- function(url, job_id)
{
    URL <- paste0(url,"/jobs/",job_id,"/stop")
    h <- c('X-Auth-Token' = authToken,'Accept'= 'text/plain')
    req <- httr::GET(URL, httr::add_headers(h))
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content)
    else
        print(content)
}

#' Trace a job
#'
#' It traces a specific current job
#'
#' @import httr
#' @param url string url of server: It must contain the server address 
#' and base url; service name will be added automatically
#' @param job_id string id of the job
#'
#' @return text trace log
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#' \dontrun{
#' 
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' list_jobs <- show_jobs_list(remote_url)
#' jobs_1 <- list_jobs$jobs[[1]]
#' trace_job(remote_url, jobs_1)
#' }
#' 
#'
#' @export
#'
trace_job <- function(url, job_id)
{
    URL <- paste0(url,"/jobs/",job_id,"/trace")
    h <- c('X-Auth-Token' = authToken,'Accept'= 'Application/json')
    req <- httr::GET(URL, httr::add_headers(h))
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content$error)
    else
        return(content)

}


#' Run GMQL query
#'
#' It runs a GMQL query as single string
#'
#' @import httr
#' @param url url of server: It must contain the server address 
#' and base url; service name is added automatically
#' @param fileName name of the file
#' @param query text of the query
#' @param output_gtf logical value indicating file format used for 
#' storing samples generated by the query.
#' The possiblities are: 
#' \itemize{
#' \item{GTF}
#' \item{TAB}
#' }
#'
#' @return None
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#'
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' run_query(remote_url, "query_1", "DATASET = SELECT() HG19_TCGA_dnaseq;
#' MATERIALIZE DATASET INTO RESULT_DS;", output_gtf = FALSE)
#'
#' @export
#'
run_query <- function(url, fileName, query, output_gtf = TRUE)
{
    if(output_gtf)
        out <- "GTF"
    else
        out <- "TAB"
    
    URL <- paste0(url,"/queries/run/",fileName,"/",out)
    h <- c('Accept' = "Application/json",
            'Content-Type' = 'text/plain','X-Auth-Token' = authToken)
    
    req <- httr::POST(URL,body = query ,httr::add_headers(h),encode = "json")
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content$error)
    else
        return(content)
}

#' Run GMQL query
#'
#' It runs a GMQL query from file
#'
#' @import httr
#' @param url string url of server: It must contain the server address 
#' and base url; service name is added automatically
#' @param fileName string name of the file
#' @param filePath string path of txt files containing a GMQL query
#' @param output_gtf logical value indicating file format used for 
#' storing samples generated by the query.
#' The possiblities are: 
#' \itemize{
#' \item{GTF}
#' \item{TAB}
#' }
#' 
#' @return None
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#'
#' ## run query: output GTF
#'
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' test_path <- system.file("example", package = "RGMQL")
#' test_query <- file.path(test_path, "query1.txt")
#' run_query(remote_url, "query_1", test_query, output_gtf = FALSE)
#'
#' @return None
#'
#' @details
#' If error occures a specific error is printed
#'
#' @export
#'
run_query_fromfile <- function(url, fileName, filePath, output_gtf = TRUE)
{
    if(!file.exists(filePath))
        stop("file does not exist")
    
    query <- readLines(filePath)
    run_query(url,fileName,query,output_gtf)
}

#' Compile GMQL query
#'
#' It compiles a GMQL query as single string using the proper GMQL web service 
#' available on a remote server
#'
#' @import httr
#' @param url string url of server: It must contain the server address 
#' and base url; service name is added automatically
#' @param query string text of the query
#'
#'
#' @return None
#'
#' @examples
#'
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' compile_query(remote_url, "DATASET = SELECT() HG19_TCGA_dnaseq;
#' MATERIALIZE DATASET INTO RESULT_DS;")
#'
#' @export
#'
compile_query <- function(url, query)
{
    h <- c('Accept' = "Application/json",
                'Content-Type' = 'text/plain','X-Auth-Token' = authToken)
    URL <- paste0(url,"/queries/compile")
    req <- httr::POST(URL,body = query ,httr::add_headers(h),encode = "json")
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content$error)
    else
        return(content)
}

#' Compile GMQL query from file
#'
#' It compiles a GMQL query from file using the proper GMQL web service 
#' available on a remote server
#'
#' @param url string url of server: It must contain the server address 
#' and base url; service name is added automatically
#' @param filePath string path of txt files containing a GMQL query
#'
#' @return None
#'
#' @details
#' If error occures a specific error is printed
#'
#' @examples
#'
#' remote_url = "http://130.186.13.219/gmql-rest"
#' login_gmql(remote_url)
#' test_path <- system.file("example", package = "RGMQL")
#' test_query <- file.path(test_path, "query1.txt")
#' compile_query_fromfile(remote_url, test_query)
#'
#' @export
#'
compile_query_fromfile <- function(url ,filePath)
{
    if(!file.exists(filePath))
        stop("file does not exist")
    
    query <- readLines(filePath)
    compile_query(url,query)
}



serialize_query <- function(url,output_gtf,base64)
{
    if(output_gtf)
        out <- "gtf"
    else
        out <- "tab"
    
    URL <- paste0(url,"/queries/dag/",out)
    h <- c('Accept' = "Application/json",
            'Content-Type' = 'text/plain','X-Auth-Token' = authToken)
    
    req <- httr::POST(URL,body = base64 ,httr::add_headers(h),encode = "json")
    content <- httr::content(req,"parsed")
    if(req$status_code !=200)
        stop(content$error)
    else
        return(content)
}
